### ISSUE TITLE
CWL does not match script

### ISSUE THREAD

**Issue by prismofeverything** [biostream/gtex-transform#2]
The script accepts three options, `--bio`, `--expression`, and `--out`, but the CWL file has one input, `--sample` and then uses a flag in arguments called `--multi`. As far as I can tell these are not supported. Not sure what's going on here.

Also, what are the expected outputs of this transform?

**Comment by kellrott** [comment]
Did this get addressed?

**Comment by prismofeverything** [comment]
Yes, we worked it out.
