### ISSUE TITLE
gct script failing

### ISSUE THREAD

**Issue by prismofeverything** [biostream/gtex-transform#9]
These two tasks are failing:

  http://funnel.compbio.ohsu.edu/v1/tasks/b9tkgevntf6iedb4pd5g
  http://funnel.compbio.ohsu.edu/v1/tasks/b9tkgevntf6iedb4pd50

The error is this:

```

panic: usage: gct <input.gct> <source> <scale>  goroutine 1 [running]: main.main() 	/opt/gct.go:26 +0x10a9
--

```

Seems like an invocation failure? Yet it shows the command above, seems okay:

    /opt/gct -filepath /in/expression.gct -source gtex -scale RPKM
    /opt/gct -filepath /in/expression.gct -source gtex -scale RPKM -gzipped

**Comment by buchanae** [comment]
https://github.com/biostream/schemas/pull/4 was merged, but doesn't trigger a rebuild here, so I had to manually trigger a rebuild. I expect this to work now.

By the way, this is more evidence why a single repo could be better. When the PR was merged, it might have triggered a rebuild of all tools/images in the repo, avoiding this issue.
